###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    ports:
      - '53002:3306'
    restart: always

  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '53000:80'
    restart: always

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdminTest6_2
    links:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - '53003:80'
    restart: always