controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_main_page:
    path: /
    controller: App\Controller\DefaultController::index

app_main_search:
    path: /search
    controller: App\Controller\DefaultController::searchAction