<?php

namespace App\Admin;

use App\Entity\Tag;
use App\Entity\Category;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Sonata\Form\Validator\ErrorElement;

final class ProductAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form): void
    {
        $form->add('name', TextType::class)
             ->add('description')
            ->add('price', IntegerType::class, ['attr' => ['class' => 'form-control', 'min' => 1, 'max' => 10000] ] )
            ->add('discount', IntegerType::class, ['attr' => ['class' => 'form-control', 'min' => 1, 'max' => 9999] ] )
             ->add('category', EntityType::class, [
                 'class' => Category::class,
                 'choice_label' => 'name',
             ]);
    }

    protected function configureDatagridFilters(DatagridMapper $datagrid): void
    {
        $datagrid->add('name')
        ->add('description')
        ;
    }

    protected function configureListFields(ListMapper $list): void
    {
        $list->addIdentifier('id')
             ->add('name')
             ->add('description')
            ->add('category.name');
    }

    protected function configureShowFields(ShowMapper $show): void
    {
        $show->add('name') ;
    }

    public function preValidate( object $object): void
    {
        dump($object);
        if($object->getDiscount() >= $object->getPrice()){
            dump("popandos");

        }
        dump($object->getPrice());
        dump($object->getDiscount());
        exit;
        parent::preValidate($object); // TODO: Change the autogenerated stub
    }
}